sudo: false
language: rust
rust:
    - nightly

cache: cargo

os:
    - linux
    - osx

env:
    - RUST_BACKTRACE=1

script:
    - cargo test --no-fail-fast
    # - cargo build --manifest-path benchmarks/Cargo.toml
    - cargo run --example simple
    - cargo run --example panic
    - cargo test --release --no-fail-fast
    - cargo run --example simple --release
    - cargo run --example panic --release
